{{- if .Values.agent.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neuroops.fullname" . }}-agent
  labels:
    {{- include "neuroops.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  replicas: {{ .Values.agent.replicaCount }}
  selector:
    matchLabels:
      {{- include "neuroops.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: agent
  template:
    metadata:
      labels:
        {{- include "neuroops.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: agent
    spec:
      containers:
        - name: agent
          image: {{ include "neuroops.image" (dict "registry" .Values.global.imageRegistry "repo" .Values.agent.image.repository "tag" .Values.agent.image.tag) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.agent.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "neuroops.fullname" . }}-config
            - secretRef:
                name: {{ include "neuroops.fullname" . }}-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
{{- end }}
