apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neuroops.fullname" . }}-secrets
  labels:
    {{- include "neuroops.labels" . | nindent 4 }}
type: Opaque
data:
  ANTHROPIC_API_KEY: {{ .Values.anthropic.apiKey | b64enc | quote }}
  GITHUB_TOKEN: {{ .Values.github.token | b64enc | quote }}
  NEUROOPS_API_KEY: {{ .Values.global.apiKey | b64enc | quote }}
  SLACK_WEBHOOK_URL: {{ .Values.app.slackWebhookUrl | b64enc | quote }}
  SLACK_API_TOKEN: {{ .Values.app.slackApiToken | b64enc | quote }}
