apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: backend-pod-delete
  namespace: neuroops-demo
  annotations:
    # ChaosResult TTL: auto-delete results after 10 minutes so the cluster stays clean
    litmuschaos.io/chaosresult-ttl: "600"
spec:
  engineState: "active"
  appinfo:
    appns: "neuroops-demo"
    applabel: "app=backend"
    appkind: "deployment"
  chaosServiceAccount: "litmus-admin"
  jobCleanUpPolicy: "delete"
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "120"
            - name: CHAOS_INTERVAL
              value: "30"
            - name: FORCE
              value: "false"
